cc_binary(
    name = "producer",
    srcs = ["producer.cc"],
    deps = ["//ipc:ipc_common"],
    copts = ["-std=c++17"],
)
cc_binary(
    name = "consumer",
    srcs = ["consumer.cc"],
    deps = ["//ipc:ipc_common"],
    copts = ["-std=c++17"],
)
