cc_binary(
    name = "decode_custom_pdu",
    srcs = ["decode_custom_pdu.cpp"],
    copts = ["-std=c++17"],
)

cc_binary(
    name = "parse_someip_pdu",
    srcs = ["parse_someip_pdu.cpp"],
    copts = ["-std=c++17"],
)
